In [ ]:
import nltk 
import re 
import numpy as np

# Creating the corpus
import pandas as pd
# Data set reference : https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences
file_path = r"C:\Users\venky\Desktop\LogisticRegression\sentiment labelled sentences\sentiment labelled sentences\imdb_labelled.txt"
df_list = []
df = pd.read_csv(file_path, names=['sentence', 'label'], sep='\t')
df_list.append(df)
df = pd.concat(df_list)
print(df)

# Train test split
sentences = df['sentence'].values
y = df['label'].values

from sklearn.model_selection import train_test_split
sentences_train, sentences_test, y_train, y_test = train_test_split(sentences, y, test_size=0.25, random_state=1000)

# Pre Processing text
def cleanup_text(dataset):
    for i in range(len(dataset)): 
        dataset[i] = dataset[i].lower() 
        dataset[i] = re.sub(r'\W', ' ', dataset[i]) 
        dataset[i] = re.sub(r'\s+', ' ', dataset[i])
    return dataset

# Creating the Bag of Words model
def create_BOW(dataset):
    word2count = {}
    for data in dataset: 
        words = nltk.word_tokenize(data) 
        for word in words: 
            if word not in word2count.keys(): 
                word2count[word] = 1
            else: 
                word2count[word] += 1
    X = [] 
    for data in dataset: 
        vector = [] 
        for word in word2count: 
            if word in nltk.word_tokenize(data): 
                vector.append(1) 
            else: 
                vector.append(0) 
        X.append(vector) 
    X = np.asarray(X)                    
    return X


 
_res1 = cleanup_text(sentences_train)
_res2 = cleanup_text(sentences_test)
X_train = create_BOW(_res1)
X_test = create_BOW(_res2)
#X_train = conv_to_vector(_res)
print(X_train)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
#score = classifier.score(X_test, y_test)
#print('Accuracy for {} data: {:.4f}'.format(source, score))

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)
print(acc_score*100)


                                              sentence  label
0    A very, very, very slow-moving, aimless movie ...      0
1    Not sure who was more lost - the flat characte...      0
2    Attempting artiness with black & white and cle...      0
3         Very little music or anything to speak of.        0
4    The best scene in the movie was when Gerardo i...      1
..                                                 ...    ...
743  I just got bored watching Jessice Lange take h...      0
744  Unfortunately, any virtue in this film's produ...      0
745                   In a word, it is embarrassing.        0
746                               Exceptionally bad!        0
747  All in all its an insult to one's intelligence...      0

[748 rows x 2 columns]
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]]


C:\Users\venky\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
