In [14]:
# NumPy provides most important object: N dimentional array known as ndarray, items should be of same type
import numpy as np
# One dimention array
a = np.array([1, 2, 3])
print('1D array')
print(a)

# Two dimention, dtype : bool, Integer, float, complex
b = np.array([[1, 2, 3], [3, 2, 1]], dtype = 'bool')
print('\n2D array')
print(b)

c = np.random.randint(10, size=(3, 4, 5))  #creates 3D array with 4 rows and 5 columns
print('\n3D array with 4 rows and 5 columns')
print(c)

1D array
[1 2 3]

2D array
[[ True  True  True]
 [ True  True  True]]

3D array
[[[6 9 1 2 5]
  [5 9 4 0 4]
  [2 4 8 9 9]
  [0 0 1 5 5]]

 [[8 1 7 1 8]
  [7 2 9 3 5]
  [9 1 3 7 7]
  [0 0 3 8 1]]

 [[2 4 6 9 0]
  [3 5 7 5 0]
  [4 2 3 0 5]
  [1 9 3 8 8]]

 [[5 8 4 9 4]
  [1 1 8 1 8]
  [2 3 5 6 5]
  [7 9 4 5 1]]]


In [2]:
# Consider 2 vectors, a = [a1, a2], b = [b1, b2]
# Create Vector
from numpy import array
va = array([2, 1, 3])
vb = array([3, 2, 4])
vx = array([2.1, 1, 0.5])
print('va: {}'.format(va))
print('vb: {}'.format(vb))
print('vx: {}'.format(vx))

#vector addition: c = a + b = (a1+b1, a2+b2)
vc = va + vb
print('Addition: {}'.format(vc))

#vector subtraction: c = a - b = (a1-b1, a2-b2)
vc = va - vb
print('Substraction: {}'.format(vc))

#vector multiplication: c = a * b = (a1*b1, a2*b2)
vc = va * vx
print('Multification: {}'.format(vc))

#vector divition: c = a / b = [a1/b1, a2/b2]
vc = va / vb
print('Divition: {}'.format(vc))

va: [2 1 3]
vb: [3 2 4]
vx: [2.1 1.  0.5]
Addition: [5 3 7]
Substraction: [-1 -1 -1]
Multification: [4.2 1.  1.5]
Divition: [0.66666667 0.5        0.75      ]


In [22]:
from numpy import array
vx = array([6, 4.1, 2])
vy = array([3, 1, 2])
print('vx: {}'.format(vx))
print('vy: {}'.format(vy))

# vector dot product: c = a.b = [a1*b1+a2*b2+a3*b3]
vc = vx.dot(vy)
print('\nvx dot product of vy: {}'.format(vc))

# vector scalar operations
# scalar multiplication vc = s * vx = [s*x1, s*x2]
sc = 0.5
vc = sc * vx
print('\nscalar multiplication {} with {} is {}'.format(sc, vx, vc))

# vector magnitude or norm (||vx||) =  square root of the sum of squares for each component of a vector
# square of each component, sum all squares, find the square root
from numpy import linalg
print('\nMagnitude of {} is {}'.format(vx, linalg.norm(vx)))

# Unit vector (^) : stripping away the magnitude,
# i.e computing the norm and then dividing each component of the vector by norm
# there is no built-in numpy function to calculate this
print('\nUnit vector of {} is {}'.format(vx, vx / linalg.norm(vx)))

vx: [6.  4.1 2. ]
vy: [3 1 2]

vx dot product of vy: 26.1

scalar multiplication 0.5 with [6.  4.1 2. ] is [3.   2.05 1.  ]

Magnitude of [6.  4.1 2. ] is 7.5372408744845085

Unit vector of [6.  4.1 2. ] is [0.79604727 0.54396563 0.26534909]


In [11]:
# https://towardsdatascience.com/linear-algebra-essentials-with-numpy-part-1-af4a867ac5ca
# Angle between vectors: widely used in NLP, when looking for strings that are very similer
# smallest angle between the vectors means strings of that vectors are very similer
# there is no direct built-in nlp function
# Angle of two vectors = dot product of two vectros / product of two vectors norm

# TF-IDF (term frequency–inverse document frequency) is the product of tf and idf
# https://en.wikipedia.org/wiki/Tf%E2%80%93idf
# the number of times a term occurs in a document is called its term frequency
# The weight of a term that occurs in a document is simply proportional to the term frequency

# An inverse document frequency factor is incorporated which diminishes the weight of terms
# that occur very frequently in the document set and increases the weight of terms that occur rarely
# The specificity of a term can be quantified as an inverse function of the number of documents in which it occurs

# Consider there are somany emails on a topic and we need to find the similar emails or 
# emails which are very close to the topic
# Convert the individual emails to vector of same dimentions, vector component will be 1 if the input contains 
# a certain word at a certain position, and 0 otherwise. 
# Now calculate the angle between vectors, the ones where angle in the smallest will be more similar

import numpy as np
ve1 = np.array([1, 4, 5])
ve2 = np.array([2, 1, 5])
dot_prd = ve1.dot(ve2)
norm_prd = np.linalg.norm(ve1) * np.linalg.norm(ve2)
print('Angle between {} and {} is {}'.format(ve1, ve2, np.rad2deg(np.arccos(dot_prd / norm_prd))))

Angle between [1 4 5] and [2 1 5] is 29.152519407030084


In [11]:
import numpy as np

A = np.matrix([
    [3, 5],
    [1, 0]
])
B = np.matrix([
    [2, -3],
    [1, 2]
])

print('Matrix A is \n{}'.format(A))
print('\nMatrix B is \n{}'.format(B))

# Matrix addition: A = [[a1, a2], [a3, a4]],  B = [[b1, b2], [b3, b4]], A+B = [[a1+b1, a2+b2], [a3+b3, a4+b4]]
print('\nAddition (A + B) is \n{}'.format(A+B))
print('\nSubtraction (A - B) is \n{}'.format(A-B))

# Scalar multiplication: A = [a1, a2, a3, a4], s * A = [[s*a1, s*a2], [s*a3, s*a4]]
s = 5
print('\nScalar multiplication ({} * A) is \n{}'.format(s, s*A)) 

Matrix A is 
[[3 5]
 [1 0]]

Matrix B is 
[[ 2 -3]
 [ 1  2]]

Addition (A + B) is 
[[5 2]
 [2 2]]

Subtraction (A - B) is 
[[ 1  8]
 [ 0 -2]]

Scalar multiplication (5 * A) is 
[[15 25]
 [ 5  0]]


In [1]:
# Matrix multiplicaton : possible only when 1st matrix colum is equal to second matrix rows
# Matrix A (m rows, n columns), Matrix B (n rows, p columns) then A X B = AB (m rows, p columns)
# Matrix multiplication: A = [[a1, a2], [a3, a4]]  B = [[b1, b2], [b3, b4]] AB = [[a1b1+a2b3, a1b2+a2b4], [a3b1+a4b3, a3b2+a4b4]]
# Matrix multiplication is the caluculation of dot product of row matrix of A and column matrix of B

import numpy as np
A = np.matrix([
    [3, 4],
    [1, 0]
])
B = np.matrix([
    [2, 2],
    [1, 2]
])

print('Matrix A is \n{}'.format(A))
print('\nMatrix B is \n{}'.format(B))
print("\nMultiplication 'A.dot(B)' is \n{}".format(A.dot(B)))
print("\nMultiplication 'np.dot(A, B)' is \n{}".format(np.dot(A,B)))

Matrix A is 
[[3 4]
 [1 0]]

Matrix B is 
[[2 2]
 [1 2]]

Multiplication 'A.dot(B)' is 
[[10 14]
 [ 2  2]]

Multiplication 'np.dot(A, B)' is 
[[10 14]
 [ 2  2]]


In [16]:
# Matrix Transpose: exchange rows and columns,
# A = [[a1, a2, a3], [a4, a5, a6]], T(A) = [[a1, a4], [a2, a5], [a3, a6]]
import numpy as np
A = np.matrix([
    [1, 2, 3],
    [4, 5, 6]
])
print('\nTranspose of \n{} is \n\n{}'.format(A, A.T))

# Identity matrix represented as I: every diagonal elements is 1, all other will be 0
print('\nGenerate identity matrix of size {} \n{}'.format(2, np.eye(2)))
print('\nGenerate identity matrix of size {} \n{}'.format(3, np.eye(3)))


Transpose of 
[[1 2 3]
 [4 5 6]] is 

[[1 4]
 [2 5]
 [3 6]]

Generate identity matrix of 2 
[[1. 0.]
 [0. 1.]]

Generate identity matrix of 3 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Determinant of a matrix (|A|) is a scalar value, computed only for any square matrix
# A = [[a, b], [c, d]] then |A| = ad - cb
import numpy as np
A = np.matrix([
    [1, 2],
    [4, 5]
])
print('\nDeterminant of \n{} is \n\n{}'.format(A, np.linalg.det(A)))

'''
A = [[a, b, c],
     [p, q, r],
     [x, y, z]] 
     
    [[a, b, c], a, b
     [p, q, r], p, q
     [x, y, z]] x, y
     
     then |A| = aqz + brx + cpy - bpz - ary - cqx
'''
B = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('\nDeterminant of \n{} is \n\n{}'.format(B, np.linalg.det(B)))


Determinant of 
[[1 2]
 [4 5]] is 

-2.9999999999999996

Determinant of 
[[1 2 3]
 [4 5 6]
 [7 8 9]] is 

0.0


In [21]:
# Matrix inverse:
'''A square matrix is called invertible (or nonsingular) if multiplication of the original matrix by its 
inverse results in the identity matrix.
conditons (1) Matrix should be square, (2) Determinant should not be ZERO
Matrix that isn't invertible is called a singular matrix
'''
# A = [[a, b], [c, d]]
# Inverse (A) = [[d, -b], [-c, a]]

# A = [[4, 3], [5, 4]]
# Inv(A) = [[4, -3], [-5, 4]]
# A * Inv(A) == I

import numpy as np
A = np.matrix([
    [4, 3],
    [5, 4]
])
print('Inverse of \n{} is \n\n{}'.format(A, np.linalg.inv(A)))

Inverse of 
[[4 3]
 [5 4]] is 

[[ 4. -3.]
 [-5.  4.]]
